codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 10%
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "internal/*/mocks/**/*"       # All mock packages
  - "internal/testutil/**/*"      # Test utilities

  - "sesh-cli/cmd/sesh/main.go"   # Main entry point

  - "scripts/**/*"                # Build/helper scripts
  - "homebrew/**/*"               # Homebrew-related files
  - "shell/**/*"                  # Shell integration files

  - "docs/**/*"                   # Documentation
  - "**/*.md"                     # Markdown files
  - "**/*.org"                    # Org mode files

  - "**/*_test.go"                # Test files (coverage shown in code being tested)
  - ".github/**/*"                # GitHub workflow files