before:
  hooks:
    - go mod tidy

builds:
  - id: sesh
    main: ./sesh-cli/cmd/sesh
    binary: sesh
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - shell/sesh.sh
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: bashhack
    name: sesh
  draft: false
  prerelease: auto
  mode: replace
  header: |
    # Sesh {{ .Version }}
    
    A CLI tool for generating AWS session credentials with MFA via TOTP.

brews:
  - name: sesh
    tap:
      owner: bashhack
      name: homebrew-tap
    description: "A CLI tool for generating AWS session credentials with MFA via TOTP"
    homepage: "https://github.com/bashhack/sesh"
    license: "MIT"
    install: |
      bin.install "sesh"
    test: |
      system "#{bin}/sesh", "--version"
