name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Verify dependencies
        run: |
          go mod tidy
          go mod verify

      - name: Lint
        run: |
          # Install linting tools
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
          go install honnef.co/go/tools/cmd/staticcheck@latest
          make lint

      - name: Build
        run: make build

      - name: Test (excluding integration tests)
        run: go test -short -v ./...
        env:
          CI: "true"

      - name: Generate coverage report
        run: |
          go test -short -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sesh
          path: ./build/sesh
